# Form implementation generated from reading ui file 'pump_gui_qtdesign_version3.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon, QFont, QDoubleValidator
import pump_official


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1171, 945)
        Form.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        
        #START; STOP; LABEL FOR HEADING
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setIcon(QIcon("image_start.png"))
        self.pushButton.setMinimumSize(QtCore.QSize(75, 0))
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setIcon(QIcon("image_stop.png"))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        #CHANNEL 1 LABELS; PUSHBUTTONS; COMBO BOXES; LINEEDITS
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setIcon(QIcon("image_start.png"))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 0, 1, 1)
        
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setIcon(QIcon("image_stop.png"))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 1, 1, 1)
        
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setIcon(QIcon("img_clockwise.png"))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 0, 1, 1)
        
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setIcon(QIcon("image_anticlockwise.png"))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 1, 1, 1)
        
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        
        #channel 1 combobox for tube diameter
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("2.54")
        self.comboBox.addItem("3.17")
        
        self.verticalLayout_2.addWidget(self.comboBox)
        
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("ml/min")
        self.comboBox_2.addItem("RPM")
        
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_15.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        
        # CHANNEL 2 BUTTONS; LINEEDITS AND COMBOBOXEWS
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setIcon(QIcon("image_start.png"))
        self.pushButton_9.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 0, 0, 1, 1)
        
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setIcon(QIcon("image_stop.png"))
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 0, 1, 1, 1)
        
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setIcon(QIcon("img_clockwise.png"))
        self.pushButton_11.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 1, 0, 1, 1)
        
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setIcon(QIcon("image_anticlockwise.png"))
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 1, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("2.54")
        self.comboBox_3.addItem("3.17")
        
        self.verticalLayout_7.addWidget(self.comboBox_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("ml/min")
        self.comboBox_4.addItem("RPM")
        
        self.horizontalLayout_7.addWidget(self.comboBox_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_12.addWidget(self.label_16)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        
        #CHANNEL 3 BUTTONS;LINEEDITS;LABELS AND COMBOBOXES
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setIcon(QIcon("image_start.png"))
        self.pushButton_17.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_4.addWidget(self.pushButton_17, 0, 0, 1, 1)
        
        self.pushButton_18 = QtWidgets.QPushButton(Form)
        self.pushButton_18.setIcon(QIcon("image_stop.png"))
        self.pushButton_18.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_4.addWidget(self.pushButton_18, 0, 1, 1, 1)
        
        self.pushButton_19 = QtWidgets.QPushButton(Form)
        self.pushButton_19.setIcon(QIcon("img_clockwise.png"))
        self.pushButton_19.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_4.addWidget(self.pushButton_19, 1, 0, 1, 1)
        
        self.pushButton_20 = QtWidgets.QPushButton(Form)
        self.pushButton_20.setIcon(QIcon("image_anticlockwise.png"))
        self.pushButton_20.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_4.addWidget(self.pushButton_20, 1, 1, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout_4)
        
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_13.addWidget(self.label_17)
        
        self.comboBox_7 = QtWidgets.QComboBox(Form)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("2.54")
        self.comboBox_7.addItem("3.17")
        
        self.verticalLayout_13.addWidget(self.comboBox_7)
        self.horizontalLayout_12.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        
        
        self.comboBox_8 = QtWidgets.QComboBox(Form)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("ml/min")
        self.comboBox_8.addItem("RPM")
        
        self.horizontalLayout_13.addWidget(self.comboBox_8)
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_13.addWidget(self.lineEdit_7)
        self.verticalLayout_14.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19)
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_14.addWidget(self.lineEdit_8)
        self.verticalLayout_14.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12.addLayout(self.verticalLayout_14)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.verticalLayout_15.addLayout(self.verticalLayout_12)
        self.horizontalLayout_15.addLayout(self.verticalLayout_15)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.horizontalLayout_15)
        

        
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        
    

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Reglo pump gui"))
        self.label.setText(_translate("Form", "               ISMATEC PUMP"))
        self.pushButton.setText(_translate("Form", "START"))
        
        
        self.pushButton_2.setText(_translate("Form", "STOP"))
        self.label_6.setText(_translate("Form", "                                                                     CHANNEL 1"))
        # self.pushButton_3.setText(_translate("Form", "START"))
        # self.pushButton_4.setText(_translate("Form", "STOP"))
        # self.pushButton_5.setText(_translate("Form", "CLOCKWISE"))
        # self.pushButton_6.setText(_translate("Form", "ANTICLOCKWISE"))
        self.label_3.setText(_translate("Form", "Tube Dia(mm)"))
        self.label_4.setText(_translate("Form", "Flowrate"))
        self.lineEdit_2.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "TIME IN SECONDS"))
        self.lineEdit.setText(_translate("Form", "0"))
        
        
        self.label_8.setText(_translate("Form", "                                                                   CHANNEL 2"))
        # self.pushButton_9.setText(_translate("Form", "START"))
        # self.pushButton_10.setText(_translate("Form", "STOP"))
        # self.pushButton_11.setText(_translate("Form", "CLOCKWISE"))
        # self.pushButton_12.setText(_translate("Form", "ANTICLOCKWISE"))
        self.label_9.setText(_translate("Form", "Tube Dia(mm)"))
        self.label_10.setText(_translate("Form", "Flowrate"))
        self.lineEdit_3.setText(_translate("Form", "0"))
        self.label_11.setText(_translate("Form", "TIME IN SECONDS"))
        self.lineEdit_4.setText(_translate("Form", "0"))
        
        self.label_16.setText(_translate("Form", "                                                                  CHANNEL 3"))
        # self.pushButton_17.setText(_translate("Form", "START"))
        # self.pushButton_18.setText(_translate("Form", "STOP"))
        # self.pushButton_19.setText(_translate("Form", "CLOCKWISE"))
        # self.pushButton_20.setText(_translate("Form", "ANTICLOCKWISE"))
        self.label_17.setText(_translate("Form", "Tube Dia(mm)"))
        self.label_18.setText(_translate("Form", "Flowrate"))
        self.lineEdit_7.setText(_translate("Form", "10"))
        self.label_19.setText(_translate("Form", "TIME IN SECONDS"))
        self.lineEdit_8.setText(_translate("Form", "0"))
        
        
        
#creating signals and slots for channel 1
        self.pushButton.clicked.connect(self.clicked_start)
        self.pushButton_2.clicked.connect(self.clicked_stop)
        
        self.pushButton_3.clicked.connect(self.clicked_flowrate_chan_1)
        self.pushButton_4.clicked.connect(self.clicked_stop_chan_1)
        
        self.pushButton_5.clicked.connect(self.clicked_cwise_chan1)
        self.pushButton_6.clicked.connect(self.clicked_Acwise_chan1)
        
        
#creating signals and slots for channel 2

        self.pushButton_9.clicked.connect(self.clicked_flowrate_chan_2)
        self.pushButton_10.clicked.connect(self.clicked_stop_chan_2)
        
        self.pushButton_11.clicked.connect(self.clicked_cwise_chan2)
        self.pushButton_12.clicked.connect(self.clicked_Acwise_chan2)

      
#creating signals and slots for channel 3
        
        self.pushButton_17.clicked.connect(self.clicked_flowrate_chan_3)
        self.pushButton_18.clicked.connect(self.clicked_stop_chan_3)
        
        self.pushButton_19.clicked.connect(self.clicked_cwise_chan3)
        self.pushButton_20.clicked.connect(self.clicked_Acwise_chan3)
        
#CALLING THE FUNCTIONS FROM PUMP FOR CHANNEL 3

    def clicked_start(self):
        pump_official.pump_obj.start_pump()
        
    def clicked_stop(self):
        pump_official.pump_obj.stop_pump()
        
    #CLOCKWISE DIRECTION
    def clicked_cwise_chan1(self):
        pump_official.pump_obj.chan_clockwise(1)
        
    #ANTICLOCKWISE DIRECTION
    def clicked_Acwise_chan1(self):
        pump_official.pump_obj.chan_Counterclockwise(1)
        
        
    def clicked_flowrate_chan_1(self):
        chan1_FR = self.lineEdit_2.text()
        chan1_time= self.lineEdit.text()
        chan1_cb_dia = self.comboBox.currentText()
        chan1_cb_setfr = self.comboBox_2.currentText()
        
        if chan1_cb_setfr == 'ml/min':
            pump_official.pump_obj.set_tubing_inner_diameter(float(chan1_cb_dia), 1)
            pump_official.pump_obj.set_runtime(float(chan1_FR), int(chan1_time), units= 's', chan =1)
            pump_official.pump_obj.start_chan(1)
            
        elif chan1_cb_setfr == 'RPM':
            pump_official.pump_obj.set_chan_RPM(1, int(chan1_FR))
            pump_official.pump_obj.start_chan(1)
    

    def clicked_stop_chan_1(self):
        pump_official.pump_obj.stop_chan(1)        
        
#CALLING THE FUNCTIONS FROM PUMP FOR CHANNEL 2
        
    #CLOCKWISE DIRECTION
    def clicked_cwise_chan2(self):
        pump_official.pump_obj.chan_clockwise(2)
        
    #ANTICLOCKWISE DIRECTION
    def clicked_Acwise_chan2(self):
        pump_official.pump_obj.chan_Counterclockwise(2)
        
        
    def clicked_flowrate_chan_2(self):
        chan3_FR = self.lineEdit_3.text()
        chan3_time= self.lineEdit_4.text()
        chan3_cb_dia = self.comboBox_3.currentText()
        chan3_cb_setfr = self.comboBox_4.currentText()
        
        if chan3_cb_setfr == 'ml/min':
            pump_official.pump_obj.set_tubing_inner_diameter(float(chan3_cb_dia), 2)
            pump_official.pump_obj.set_runtime(float(chan3_FR), int(chan3_time), units= 's', chan =2)
            pump_official.pump_obj.start_chan(2)
            
        elif chan3_cb_setfr == 'RPM':
            pump_official.pump_obj.set_chan_RPM(2, int(chan3_FR))
            pump_official.pump_obj.start_chan(2)
    

    def clicked_stop_chan_2(self):
        pump_official.pump_obj.stop_chan(2)


#CALLING THE FUNCTIONS FROM PUMP FOR CHANNEL 3

    #CLOCKWISE DIRECTION
    def clicked_cwise_chan3(self):
        pump_official.pump_obj.chan_clockwise(3)
        
    #ANTICLOCKWISE DIRECTION
    def clicked_Acwise_chan3(self):
        pump_official.pump_obj.chan_Counterclockwise(3)
        
        
    def clicked_flowrate_chan_3(self):
        chan3_FR = self.lineEdit_7.text()
        chan3_time= self.lineEdit_8.text()
        chan3_cb_dia = self.comboBox_7.currentText()
        chan3_cb_setfr = self.comboBox_8.currentText()
        
        if chan3_cb_setfr == 'ml/min':
            pump_official.pump_obj.set_tubing_inner_diameter(float(chan3_cb_dia), 3)
            pump_official.pump_obj.set_runtime(float(chan3_FR), int(chan3_time), units= 's', chan =3)
            pump_official.pump_obj.start_chan(3)
            
        elif chan3_cb_setfr == 'RPM':
            pump_official.pump_obj.set_chan_RPM(3, int(chan3_FR))
            pump_official.pump_obj.start_chan(3)
    

    def clicked_stop_chan_3(self):
        pump_official.pump_obj.stop_chan(3)
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
